<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>umbral_backend.Infrastructure</RootNamespace>
    <AssemblyName>umbral_backend.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
