import { Stack, useRouter, useSegments, type Href } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useRef } from 'react';
import { AppState } from 'react-native';
import { AuthProvider, useAuth } from '@/lib/auth/use-auth';
import { loadReconnectContext } from '@/lib/realtime/reconnect-context';

function AuthGuard() {
  const { status } = useAuth();
  const router = useRouter();
  // Cast to string[] — typed routes are regenerated by the dev server; casts are
  // safe since the runtime values are plain strings.
  const segments = useSegments() as unknown as string[];

  useEffect(() => {
    if (status === 'authenticating') return;

    const inApp = segments[0] === '(app)';
    const inAuth = segments[0] === '(auth)';
    const inLogin = inAuth && segments[1] === 'login';
    // register is an anonymous entry point (ADR-0016 §1) — like login, an unauthenticated user must
    // be able to stay on it instead of being bounced back to the login screen.
    const inRegister = inAuth && segments[1] === 'register';

    if (status === 'authenticated' && !inApp) {
      router.replace('/(app)' as Href);
    } else if (status === 'rejected') {
      if (!(inAuth && segments[1] === 'access-denied')) {
        router.replace('/(auth)/access-denied' as Href);
      }
    } else if ((status === 'idle' || status === 'error') && !inLogin && !inRegister) {
      router.replace('/(auth)/login' as Href);
    }
  }, [status, segments]);

  return null;
}

/**
 * Routes an authenticated participant who has a persisted live context back into
 * `team-space` — on a cold start (app killed) and when the app returns to the
 * foreground — so resuming doesn't replay the join flow. team-space itself owns
 * the actual `ReconnectAsync` invoke; this only puts the user on that surface.
 */
function ReconnectResume() {
  const { status } = useAuth();
  const router = useRouter();
  const segments = useSegments() as unknown as string[];
  const appState = useRef(AppState.currentState);
  const coldStartChecked = useRef(false);

  const resume = useCallback(async () => {
    const inTeamSpace = segments[0] === '(app)' && segments[1] === 'team-space';
    if (inTeamSpace) return;
    const context = await loadReconnectContext();
    if (context) {
      router.replace('/(app)/team-space' as Href);
    }
  }, [router, segments]);

  // Cold start: once auth settles, restore into the live surface if context exists.
  useEffect(() => {
    if (status !== 'authenticated' || coldStartChecked.current) return;
    coldStartChecked.current = true;
    void resume();
  }, [status, resume]);

  // Warm resume: on background → active while authenticated.
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (next) => {
      const wasBackground = /inactive|background/.test(appState.current);
      appState.current = next;
      if (next === 'active' && wasBackground && status === 'authenticated') {
        void resume();
      }
    });
    return () => subscription.remove();
  }, [status, resume]);

  return null;
}

export default function RootLayout() {
  return (
    <AuthProvider>
      <StatusBar style="dark" />
      <AuthGuard />
      <ReconnectResume />
      <Stack screenOptions={{ headerShown: false }} />
    </AuthProvider>
  );
}
