import { Stack, useRouter, useSegments, type Href } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { AuthProvider, useAuth } from '@/lib/auth/use-auth';

function AuthGuard() {
  const { status } = useAuth();
  const router = useRouter();
  // Cast to string[] — typed routes are regenerated by the dev server; casts are
  // safe since the runtime values are plain strings.
  const segments = useSegments() as unknown as string[];

  useEffect(() => {
    if (status === 'authenticating') return;

    const inApp = segments[0] === '(app)';
    const inAuth = segments[0] === '(auth)';
    const inLogin = inAuth && segments[1] === 'login';

    if (status === 'authenticated' && !inApp) {
      router.replace('/(app)' as Href);
    } else if (status === 'rejected') {
      if (!(inAuth && segments[1] === 'access-denied')) {
        router.replace('/(auth)/access-denied' as Href);
      }
    } else if ((status === 'idle' || status === 'error') && !inLogin) {
      router.replace('/(auth)/login' as Href);
    }
  }, [status, segments]);

  return null;
}

export default function RootLayout() {
  return (
    <AuthProvider>
      <StatusBar style="dark" />
      <AuthGuard />
      <Stack screenOptions={{ headerShown: false }} />
    </AuthProvider>
  );
}
