// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using umbral_backend.Infrastructure.Persistence;

#nullable disable

namespace umbral_backend.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260604014217_AddAssociatedTeamReferenceCorrelation")]
partial class AddAssociatedTeamReferenceCorrelation
{
}
