// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using umbral_backend.Infrastructure.Persistence;

#nullable disable

namespace umbral_backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("umbral_backend.Domain.Entities.LiveSession", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("active_question_index");

                    b.Property<Guid?>("ActiveSubstageId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_substage_id");

                    b.Property<int?>("AssignedOperatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_operator_user_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("LastStateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_state_changed_at");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_code");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("state_reason");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_snapshot");

                    b.Property<DateTimeOffset?>("_questionTimerAdvancingSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("question_timer_advancing_since");

                    b.Property<DateTimeOffset?>("_questionTimerExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("question_timer_expired_at");

                    b.Property<TimeSpan>("_questionTimerRemainingDuration")
                        .HasColumnType("interval")
                        .HasColumnName("question_timer_remaining_duration");

                    b.Property<TimeSpan>("_questionTimerTotalDuration")
                        .HasColumnType("interval")
                        .HasColumnName("question_timer_total_duration");

                    b.HasKey("LiveSessionId");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.ToTable("live_sessions", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.LiveSession", b =>
                {
                    b.OwnsMany("umbral_backend.Domain.Entities.JoinContext", "JoinContexts", b1 =>
                        {
                            b1.Property<Guid>("JoinContextId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("ConsumedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("consumed_at");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<Guid?>("JoinTokenId")
                                .HasColumnType("uuid")
                                .HasColumnName("join_token_id");

                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("live_session_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<Guid?>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.HasKey("JoinContextId");

                            b1.HasIndex("LiveSessionId", "TeamId");

                            b1.ToTable("live_session_join_contexts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");
                        });

                    b.OwnsOne("umbral_backend.Domain.ValueObjects.MaximumTime", "MaximumTime", b1 =>
                        {
                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("maximum_time_minutes");

                            b1.HasKey("LiveSessionId");

                            b1.ToTable("live_sessions");

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");
                        });

                    b.OwnsMany("umbral_backend.Domain.Entities.SessionParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("SessionParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<Guid>("ExternalIdentityId")
                                .HasColumnType("uuid")
                                .HasColumnName("external_identity_id");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<DateTimeOffset>("LastSeenAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_seen_at");

                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("live_session_id");

                            b1.Property<string>("ParticipantStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("participant_status");

                            b1.HasKey("SessionParticipantId");

                            b1.HasIndex("LiveSessionId", "ExternalIdentityId")
                                .IsUnique();

                            b1.ToTable("live_session_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");
                        });

                    b.OwnsMany("umbral_backend.Domain.Entities.Team", "Teams", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer")
                                .HasColumnName("team_capacity");

                            b1.Property<Guid?>("CurrentClueNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("current_clue_node_id");

                            b1.Property<Guid?>("CurrentProgressNodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("current_progress_node_id");

                            b1.Property<int?>("CurrentScore")
                                .HasColumnType("integer")
                                .HasColumnName("current_score");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<string>("JoinStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("join_status");

                            b1.Property<DateTimeOffset?>("LastScoreCalculatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_score_calculated_at");

                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("live_session_id");

                            b1.Property<Guid?>("ReferenceTeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("reference_team_id");

                            b1.Property<int>("ReleasedClueCount")
                                .HasColumnType("integer")
                                .HasColumnName("released_clue_count");

                            b1.Property<string>("TeamCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("team_code");

                            b1.HasKey("TeamId");

                            b1.HasIndex("LiveSessionId", "ReferenceTeamId")
                                .IsUnique();

                            b1.HasIndex("LiveSessionId", "TeamCode")
                                .IsUnique();

                            b1.ToTable("live_session_teams", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");

                            b1.OwnsMany("umbral_backend.Domain.Entities.TeamMember", "Members", b2 =>
                                {
                                    b2.Property<Guid>("TeamMemberId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("JoinedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("joined_at");

                                    b2.Property<DateTimeOffset?>("LeftAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("left_at");

                                    b2.Property<string>("MembershipStatus")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("membership_status");

                                    b2.Property<Guid>("SessionParticipantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("session_participant_id");

                                    b2.Property<Guid>("TeamId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("team_id");

                                    b2.HasKey("TeamMemberId");

                                    b2.HasIndex("TeamId", "SessionParticipantId")
                                        .IsUnique();

                                    b2.ToTable("live_session_team_members", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TeamId");
                                });

                            b1.Navigation("Members");
                        });

                    b.OwnsMany("umbral_backend.Domain.Entities.TriviaAnswerSubmission", "TriviaAnswerSubmissions", b1 =>
                        {
                            b1.Property<Guid>("EvidenceSubmissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ActiveSubstageId")
                                .HasColumnType("uuid")
                                .HasColumnName("active_substage_id");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean")
                                .HasColumnName("is_correct");

                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("live_session_id");

                            b1.Property<int>("QuestionSequenceOrder")
                                .HasColumnType("integer")
                                .HasColumnName("question_sequence_order");

                            b1.Property<int>("ScoreValue")
                                .HasColumnType("integer")
                                .HasColumnName("score_value");

                            b1.Property<int>("SelectedOptionSequenceOrder")
                                .HasColumnType("integer")
                                .HasColumnName("selected_option_sequence_order");

                            b1.Property<string>("SubmissionType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("submission_type");

                            b1.Property<DateTimeOffset>("SubmittedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("submitted_at");

                            b1.Property<Guid?>("SubmittedByParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("submitted_by_participant_id");

                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<string>("ValidationState")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("validation_state");

                            b1.HasKey("EvidenceSubmissionId");

                            b1.HasIndex("LiveSessionId", "TeamId", "ActiveSubstageId", "QuestionSequenceOrder")
                                .IsUnique();

                            b1.ToTable("live_session_trivia_answer_submissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");
                        });

                    b.OwnsOne("umbral_backend.Domain.ValueObjects.SessionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("LiveSessionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SourceEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_entity_id");

                            b1.Property<string>("SourceType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("source_entity_type");

                            b1.HasKey("LiveSessionId");

                            b1.ToTable("live_sessions");

                            b1.WithOwner()
                                .HasForeignKey("LiveSessionId");
                        });

                    b.OwnsOne("umbral_backend.Domain.Entities.MissionRuntimeSnapshot", "MissionRuntimeSnapshot", b1 =>
                        {
                            b1.Property<Guid>("live_session_id")
                                .HasColumnType("uuid")
                                .HasColumnName("live_session_id");

                            b1.Property<Guid>("MissionRuntimeSnapshotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("MissionTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mission_title");

                            b1.Property<Guid>("SourceMissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_mission_id");

                            b1.HasKey("live_session_id");

                            b1.ToTable("live_session_mission_runtime_snapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("live_session_id");

                            b1.OwnsOne("umbral_backend.Domain.ValueObjects.MaximumTime", "MaximumTime", b2 =>
                                {
                                    b2.Property<Guid>("MissionRuntimeSnapshotlive_session_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Minutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("maximum_time_minutes");

                                    b2.HasKey("MissionRuntimeSnapshotlive_session_id");

                                    b2.ToTable("live_session_mission_runtime_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("MissionRuntimeSnapshotlive_session_id");
                                });

                            b1.OwnsMany("umbral_backend.Domain.ValueObjects.StageSnapshot", "StageSnapshots", b2 =>
                                {
                                    b2.Property<Guid>("StageSnapshotId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("SequenceOrder")
                                        .HasColumnType("integer")
                                        .HasColumnName("sequence_order");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("title");

                                    b2.Property<Guid>("mission_runtime_snapshot_live_session_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("live_session_id");

                                    b2.HasKey("StageSnapshotId");

                                    b2.HasIndex("mission_runtime_snapshot_live_session_id", "SequenceOrder")
                                        .IsUnique();

                                    b2.ToTable("live_session_mission_runtime_snapshot_stages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("mission_runtime_snapshot_live_session_id");

                                    b2.OwnsMany("umbral_backend.Domain.ValueObjects.SubstageSnapshot", "SubstageSnapshots", b3 =>
                                        {
                                            b3.Property<Guid>("SubstageSnapshotId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<string>("PlayMode")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("character varying(32)")
                                                .HasColumnName("play_mode");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer")
                                                .HasColumnName("sequence_order");

                                            b3.Property<string>("Title")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("title");

                                            b3.Property<int?>("WinnerScore")
                                                .HasColumnType("integer")
                                                .HasColumnName("winner_score");

                                            b3.Property<Guid>("stage_snapshot_id")
                                                .HasColumnType("uuid")
                                                .HasColumnName("stage_snapshot_id");

                                            b3.HasKey("SubstageSnapshotId");

                                            b3.HasIndex("stage_snapshot_id", "SequenceOrder")
                                                .IsUnique();

                                            b3.ToTable("live_session_mission_runtime_snapshot_substages", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("stage_snapshot_id");
                                        });

                                    b2.Navigation("SubstageSnapshots");
                                });

                            b1.OwnsMany("umbral_backend.Domain.ValueObjects.TargetSnapshot", "TargetSnapshots", b2 =>
                                {
                                    b2.Property<Guid>("TargetSnapshotId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("ClueText")
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasColumnName("clue_text");

                                    b2.Property<string>("ClueVisibilityPolicy")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("clue_visibility_policy");

                                    b2.Property<bool>("IsActive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_active");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("name");

                                    b2.Property<string>("QrCode")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("qr_code");

                                    b2.Property<int>("SequenceOrder")
                                        .HasColumnType("integer")
                                        .HasColumnName("sequence_order");

                                    b2.Property<Guid>("SubstageSnapshotId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("substage_snapshot_id");

                                    b2.Property<Guid>("mission_runtime_snapshot_live_session_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("live_session_id");

                                    b2.HasKey("TargetSnapshotId");

                                    b2.HasIndex("mission_runtime_snapshot_live_session_id", "QrCode")
                                        .IsUnique();

                                    b2.HasIndex("mission_runtime_snapshot_live_session_id", "SubstageSnapshotId", "SequenceOrder")
                                        .IsUnique()
                                        .HasDatabaseName("IX_live_session_mission_runtime_snapshot_targets_live_session~1");

                                    b2.ToTable("live_session_mission_runtime_snapshot_targets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("mission_runtime_snapshot_live_session_id");
                                });

                            b1.OwnsMany("umbral_backend.Domain.ValueObjects.TriviaQuestionSnapshot", "TriviaQuestionSnapshots", b2 =>
                                {
                                    b2.Property<int>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("id"));

                                    b2.Property<string>("Explanation")
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasColumnName("explanation");

                                    b2.Property<string>("Prompt")
                                        .IsRequired()
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)")
                                        .HasColumnName("prompt");

                                    b2.Property<int>("ScoreValue")
                                        .HasColumnType("integer")
                                        .HasColumnName("score_value");

                                    b2.Property<int>("SequenceOrder")
                                        .HasColumnType("integer")
                                        .HasColumnName("sequence_order");

                                    b2.Property<Guid>("SubstageSnapshotId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("substage_snapshot_id");

                                    b2.Property<int>("TimeLimitSeconds")
                                        .HasColumnType("integer")
                                        .HasColumnName("time_limit_seconds");

                                    b2.Property<Guid>("mission_runtime_snapshot_live_session_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("live_session_id");

                                    b2.HasKey("id");

                                    b2.HasIndex("mission_runtime_snapshot_live_session_id", "SubstageSnapshotId", "SequenceOrder")
                                        .IsUnique();

                                    b2.ToTable("live_session_mission_runtime_snapshot_trivia_questions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("mission_runtime_snapshot_live_session_id");

                                    b2.OwnsMany("umbral_backend.Domain.ValueObjects.TriviaOptionSnapshot", "Options", b3 =>
                                        {
                                            b3.Property<int>("id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("id"));

                                            b3.Property<bool>("IsCorrect")
                                                .HasColumnType("boolean")
                                                .HasColumnName("is_correct");

                                            b3.Property<string>("OptionText")
                                                .IsRequired()
                                                .HasMaxLength(2000)
                                                .HasColumnType("character varying(2000)")
                                                .HasColumnName("option_text");

                                            b3.Property<int>("SequenceOrder")
                                                .HasColumnType("integer")
                                                .HasColumnName("sequence_order");

                                            b3.Property<int>("trivia_question_snapshot_id")
                                                .HasColumnType("integer")
                                                .HasColumnName("trivia_question_snapshot_id");

                                            b3.HasKey("id");

                                            b3.HasIndex("trivia_question_snapshot_id", "SequenceOrder")
                                                .IsUnique();

                                            b3.ToTable("live_session_mission_runtime_snapshot_trivia_options", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("trivia_question_snapshot_id");
                                        });

                                    b2.Navigation("Options");
                                });

                            b1.Navigation("MaximumTime")
                                .IsRequired();

                            b1.Navigation("StageSnapshots");

                            b1.Navigation("TargetSnapshots");

                            b1.Navigation("TriviaQuestionSnapshots");
                        });

                    b.Navigation("JoinContexts");

                    b.Navigation("MaximumTime")
                        .IsRequired();

                    b.Navigation("MissionRuntimeSnapshot")
                        .IsRequired();

                    b.Navigation("Participants");

                    b.Navigation("Source")
                        .IsRequired();

                    b.Navigation("Teams");

                    b.Navigation("TriviaAnswerSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
