// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using umbral_backend.Infrastructure.Persistence;

#nullable disable

namespace umbral_backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707030159_RenameTeamsToRegisteredTeams")]
    partial class RenameTeamsToRegisteredTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("umbral_backend.Domain.Entities.JoinToken", b =>
                {
                    b.Property<Guid>("JoinTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<int>("IssuedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("issued_by_user_id");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.HasKey("JoinTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("LiveSessionId", "TeamId", "Status");

                    b.ToTable("join_tokens", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.LiveSessionReference", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("session_code");

                    b.HasKey("LiveSessionId");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.ToTable("live_sessions", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.RegisteredTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_code");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamCode")
                        .IsUnique();

                    b.ToTable("registered_teams", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.RegisteredTeamMembership", b =>
                {
                    b.Property<Guid>("TeamMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TeamMembershipId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("registered_team_memberships", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.SessionTeamAssociation", b =>
                {
                    b.Property<Guid>("SessionTeamAssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("SessionTeamAssociationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LiveSessionId", "TeamId")
                        .IsUnique();

                    b.ToTable("session_team_associations", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIdentityId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.RegisteredTeamMembership", b =>
                {
                    b.HasOne("umbral_backend.Domain.Entities.RegisteredTeam", null)
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("umbral_backend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.SessionTeamAssociation", b =>
                {
                    b.HasOne("umbral_backend.Domain.Entities.LiveSessionReference", null)
                        .WithMany("TeamAssociations")
                        .HasForeignKey("LiveSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("umbral_backend.Domain.Entities.RegisteredTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.LiveSessionReference", b =>
                {
                    b.Navigation("TeamAssociations");
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.RegisteredTeam", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
