// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using umbral_backend.Infrastructure.Persistence;

#nullable disable

namespace umbral_backend.Infrastructure.Migrations
{
    [DbContext(typeof(ScoringMonitoringDbContext))]
    [Migration("20260717024347_AddSessionEventTeamAndExternalActor")]
    partial class AddSessionEventTeamAndExternalActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("umbral_backend.Domain.Entities.Penalty", b =>
                {
                    b.Property<Guid>("PenaltyId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<string>("PenaltyReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("penalty_reason");

                    b.Property<Guid>("ScoreEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_entry_id");

                    b.HasKey("PenaltyId");

                    b.HasIndex("ScoreEntryId")
                        .IsUnique();

                    b.ToTable("penalties", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.Ranking", b =>
                {
                    b.Property<Guid>("RankingId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CalculationVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_version");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.HasKey("RankingId");

                    b.HasIndex("LiveSessionId")
                        .IsUnique();

                    b.ToTable("rankings", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.ScoreEntry", b =>
                {
                    b.Property<Guid>("ScoreEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("RecordedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer")
                        .HasColumnName("score_value");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_entity_type");

                    b.Property<string>("TeamDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_display_name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("ScoreEntryId");

                    b.HasIndex("LiveSessionId", "TeamId");

                    b.HasIndex("SourceEntityType", "SourceEntityId")
                        .IsUnique();

                    b.ToTable("score_entries", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.SessionEvent", b =>
                {
                    b.Property<Guid>("SessionEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payload_summary");

                    b.Property<Guid?>("ResponsibleUserExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_user_external_id");

                    b.Property<string>("SourceEventKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_event_key");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("SessionEventId");

                    b.HasIndex("SourceEventKey")
                        .IsUnique()
                        .HasDatabaseName("ux_session_events_source_event_key");

                    b.HasIndex("LiveSessionId", "OccurredAt");

                    b.HasIndex("LiveSessionId", "TeamId", "OccurredAt");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.SessionOperatorAssignmentProjection", b =>
                {
                    b.Property<Guid>("LiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("live_session_id");

                    b.Property<Guid>("AssignedOperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_operator_user_id");

                    b.HasKey("LiveSessionId");

                    b.ToTable("session_operator_assignments", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.Penalty", b =>
                {
                    b.HasOne("umbral_backend.Domain.Entities.ScoreEntry", null)
                        .WithOne()
                        .HasForeignKey("umbral_backend.Domain.Entities.Penalty", "ScoreEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.Ranking", b =>
                {
                    b.OwnsMany("umbral_backend.Domain.Entities.Ranking+Row", "Rows", b1 =>
                        {
                            b1.Property<Guid>("ranking_id")
                                .HasColumnType("uuid")
                                .HasColumnName("ranking_id");

                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<TimeSpan?>("ResolutionTime")
                                .HasColumnType("interval")
                                .HasColumnName("resolution_time");

                            b1.Property<string>("TeamDisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("team_display_name");

                            b1.Property<int>("TotalScore")
                                .HasColumnType("integer")
                                .HasColumnName("total_score");

                            b1.HasKey("ranking_id", "TeamId");

                            b1.HasIndex("ranking_id", "Position");

                            b1.ToTable("ranking_rows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ranking_id");
                        });

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
