// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using umbral_backend.Infrastructure.Persistence;

#nullable disable

namespace umbral_backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603141753_AddTriviaQuizLineageAndUsageHistory")]
    partial class AddTriviaQuizLineageAndUsageHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("umbral_backend.Domain.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.TriviaQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("HasUsageHistory")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SourceTriviaQuizId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SourceTriviaQuizId");

                    b.HasIndex("Status");

                    b.ToTable("TriviaQuizzes", (string)null);
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.Mission", b =>
                {
                    b.OwnsOne("umbral_backend.Domain.ValueObjects.Difficulty", "Difficulty", b1 =>
                        {
                            b1.Property<int>("MissionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Difficulty");

                            b1.HasKey("MissionId");

                            b1.ToTable("Missions");

                            b1.WithOwner()
                                .HasForeignKey("MissionId");
                        });

                    b.OwnsOne("umbral_backend.Domain.ValueObjects.MaximumTime", "MaximumTime", b1 =>
                        {
                            b1.Property<int>("MissionId")
                                .HasColumnType("integer");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("MaximumTimeMinutes");

                            b1.HasKey("MissionId");

                            b1.ToTable("Missions");

                            b1.WithOwner()
                                .HasForeignKey("MissionId");
                        });

                    b.Navigation("Difficulty")
                        .IsRequired();

                    b.Navigation("MaximumTime")
                        .IsRequired();
                });

            modelBuilder.Entity("umbral_backend.Domain.Entities.TriviaQuiz", b =>
                {
                    b.OwnsMany("umbral_backend.Domain.Entities.TriviaQuestion", "Questions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Explanation")
                                .HasColumnType("text");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int?>("ScoreValue")
                                .HasColumnType("integer");

                            b1.Property<int>("SequenceOrder")
                                .HasColumnType("integer");

                            b1.Property<int>("TriviaQuizId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TriviaQuizId", "SequenceOrder")
                                .IsUnique();

                            b1.ToTable("TriviaQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TriviaQuizId");

                            b1.OwnsMany("umbral_backend.Domain.Entities.TriviaOption", "Options", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("IsCorrect")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("OptionText")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)");

                                    b2.Property<int>("SequenceOrder")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TriviaQuestionId")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TriviaQuestionId", "SequenceOrder")
                                        .IsUnique();

                                    b2.ToTable("TriviaOptions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TriviaQuestionId");
                                });

                            b1.OwnsOne("umbral_backend.Domain.ValueObjects.QuestionTimer", "TimeLimit", b2 =>
                                {
                                    b2.Property<int>("TriviaQuestionId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Seconds")
                                        .HasColumnType("integer")
                                        .HasColumnName("TimeLimitSeconds");

                                    b2.HasKey("TriviaQuestionId");

                                    b2.ToTable("TriviaQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("TriviaQuestionId");
                                });

                            b1.Navigation("Options");

                            b1.Navigation("TimeLimit");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
