<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>umbral_backend.Application.FunctionalTests</RootNamespace>
        <AssemblyName>umbral_backend.Application.FunctionalTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="nunit" />
      <PackageReference Include="NUnit.Analyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NUnit3TestAdapter" />
      <PackageReference Include="coverlet.collector">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Shouldly" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Api\Api.csproj" />
    </ItemGroup>

</Project>
